dumpFile: ./data/source.tar.gz
outputFile: ./output/filtered_result.tar.gz
tmpDir: ./tmp
maxLineBytes: 8388608
dbDriver: mysql
mode: schedule
scheduleEvery: 1h
filterRules:
  - action: ddl
    tables:
      - ^tmp_
      - ^log_
  - action: insert
    tables:
      - ^tmp_
      - ^log_
